### ISSUE TITLE
Will not compile with libnet 1.1

### ISSUE THREAD

**Issue by pedrovanzella** [tecknicaltom/dsniff#1]
make throws:

./arpspoof.c: In function ‘arp_send’:
./arpspoof.c:51: error: too many arguments to function ‘libnet_get_hwaddr’
./arpspoof.c:62: error: too few arguments to function ‘libnet_build_ethernet’
./arpspoof.c:66: error: ‘ETH_H’ undeclared (first use in this function)
./arpspoof.c:66: error: (Each undeclared identifier is reported only once
./arpspoof.c:66: error: for each function it appears in.)
./arpspoof.c:66: error: too few arguments to function ‘libnet_build_arp’
make: **\* [arpspoof.o] Error 1

**Comment by dethe** [comment]
I'm having this same problem, any work-arounds? I'm on OS X 10.6 using libnet insalled from  homebrew.

**Comment by franciscolourenco** [comment]
me too.
~/Downloads/dsniff-2.3/make                                                                                                                                            (05-04 17:24)
gcc -g -O2 -D_BSD_SOURCE -DHAVE_SOCKADDR_SA_LEN -DDSNIFF_LIBDIR=\"/usr/local/lib/\" -I. -I/usr/local/include -I/usr/include/pcap -I/usr/local/include    -I./missing -c ./missing/dummy.c
gcc -g -O2 -D_BSD_SOURCE -DHAVE_SOCKADDR_SA_LEN -DDSNIFF_LIBDIR=\"/usr/local/lib/\" -I. -I/usr/local/include -I/usr/include/pcap -I/usr/local/include    -I./missing -c ./missing/md5.c
ar -cr libmissing.a dummy.o  md5.o
/usr/bin/ranlib: file: libmissing.a(dummy.o) has no symbols
ranlib libmissing.a
ranlib: file: libmissing.a(dummy.o) has no symbols
gcc -g -O2 -D_BSD_SOURCE -DHAVE_SOCKADDR_SA_LEN -DDSNIFF_LIBDIR=\"/usr/local/lib/\" -I. -I/usr/local/include -I/usr/include/pcap -I/usr/local/include    -I./missing -c ./arpspoof.c
./arpspoof.c:25: warning: ‘struct ether_addr’ declared inside parameter list
./arpspoof.c:25: warning: its scope is only this definition or declaration, which is probably not what you want
./arpspoof.c:26: warning: ‘struct ether_addr’ declared inside parameter list
./arpspoof.c: In function ‘arp_send’:
./arpspoof.c:49: warning: passing argument 1 of ‘libnet_get_hwaddr’ from incompatible pointer type
./arpspoof.c:49: error: too many arguments to function ‘libnet_get_hwaddr’
./arpspoof.c:60: warning: passing argument 6 of ‘libnet_build_ethernet’ from incompatible pointer type
./arpspoof.c:60: error: too few arguments to function ‘libnet_build_ethernet’
./arpspoof.c:64: error: ‘ETH_H’ undeclared (first use in this function)
./arpspoof.c:64: error: (Each undeclared identifier is reported only once
./arpspoof.c:64: error: for each function it appears in.)
./arpspoof.c:64: error: too few arguments to function ‘libnet_build_arp’
./arpspoof.c:67: warning: passing argument 1 of ‘ether_ntoa’ from incompatible pointer type
./arpspoof.c:71: warning: passing argument 1 of ‘ether_ntoa’ from incompatible pointer type
./arpspoof.c:73: warning: format ‘%s’ expects type ‘char _’, but argument 4 has type ‘int’
./arpspoof.c:73: warning: format ‘%s’ expects type ‘char *’, but argument 5 has type ‘int’
./arpspoof.c:77: warning: passing argument 1 of ‘ether_ntoa’ from incompatible pointer type
./arpspoof.c:78: warning: format ‘%s’ expects type ‘char *’, but argument 4 has type ‘int’
./arpspoof.c:80: warning: passing argument 1 of ‘ether_ntoa’ from incompatible pointer type
./arpspoof.c: In function ‘arp_find’:
./arpspoof.c:114: warning: passing argument 2 of ‘arp_cache_lookup’ from incompatible pointer type
./arpspoof.c: In function ‘main’:
./arpspoof.c:181: warning: assignment makes pointer from integer without a cast
make: *_\* [arpspoof.o] Error 1

**Comment by t-mdo** [comment]
Same here.. No solution yet ?

**Comment by defensahacker** [comment]
Done.
https://github.com/spinfoo/dsniff-ng
